### ISSUE TITLE
Update to the NEWEST FreeRTOS?

### ISSUE THREAD

**Issue by jiapei100** [QuickLogic-Corp/qorc-sdk#156]
`uxTaskGetTCBNumber` seems to be NOT in the [NEWEST FreeRTOS](https://github.com/FreeRTOS/FreeRTOS) .

There should be an update of [qorc-sdk's FreeRTOS](https://github.com/QuickLogic-Corp/qorc-sdk/tree/master/FreeRTOS) ?

**Comment by jiapei100** [comment]
And, even if without upgrading **FreeRTOS**, sticking to the current git of year 2020, I got the following **ERROR** messages:

```console
➜  qorc-sdk git:(master) ✗ python ./TinyFPGA-Programmer-Application/tinyfpga-programmer-gui.py --port /dev/ttyACM0 --m4app ./qf_apps/qf_helloworldsw/GCC_Project/output/bin/qf_helloworldsw.bin --mode m4
CLI mode
ports =  ['/dev/ttyACM0 (QuickFeather)'] 1
Using port  /dev/ttyACM0 (QuickFeather)
Programming m4 application with  ./qf_apps/qf_helloworldsw/GCC_Project/output/bin/qf_helloworldsw.bin
Erasing designated flash pages
Erase  64.0 KiB ( 0xd8 ) at  0x80000
Erase  32.0 KiB ( 0x52 ) at  0x90000
Erase  4.0 KiB ( 0x20 ) at  0x98000
Erase  4.0 KiB ( 0x20 ) at  0x99000
Erase  4.0 KiB ( 0x20 ) at  0x9a000
Erase  4.0 KiB ( 0x20 ) at  0x9b000
Erase  4.0 KiB ( 0x20 ) at  0x9c000
Writing  binary
Write  117808  bytes
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTraceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/serial/serialposix.py", line 621, in write
    n = os.write(self.fd, d)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "....../qorc-sdk/./TinyFPGA-Programmer-Application/tinyfpga-programmer-gui.py", line 206, in program
    fpga.program_bitstream(addr, bitstream, "binary")
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 311, in program_bitstream
    if self.program(addr, bitstream, what):
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 233, in program
    self.write(addr, data)
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 216, in write
    self._write(addr, data[:write_length])
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 204, in _write
    self.wait_while_busy()
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 99, in wait_while_busy
    while ord(self.read_sts()) & 1:
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 60, in read_sts
    return self.cmd(0x05, read_len=1) or '1'
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 43, in cmd
    self.ser.write(bytearray(cmd_write_string))
  File "~/.local/lib/python3.10/site-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
serial.serialutil.SerialException: write failed: [Errno 5] Input/output error
Writing metadata
Erasing designated flash pages
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/serial/serialposix.py", line 621, in write
    n = os.write(self.fd, d)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "....../qorc-sdk/./TinyFPGA-Programmer-Application/tinyfpga-programmer-gui.py", line 218, in program
    fpga.program_bitstream(meta_addr, meta_bitstream, "metadata")
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 311, in program_bitstream
    if self.program(addr, bitstream, what):
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 229, in program
    self.quick_erase(addr, len(data))
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 179, in quick_erase
    self._erase(start_addr, 0x1000)
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 108, in _erase
    self.write_enable()
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 86, in write_enable
    self.cmd(0x06)
  File "....../qorc-sdk/TinyFPGA-Programmer-Application/q-series/python/tinyfpgaq.py", line 43, in cmd
    self.ser.write(bytearray(cmd_write_string))
  File "~/.local/lib/python3.10/site-packages/serial/serialposix.py", line 655, in write
    raise SerialException('write failed: {}'.format(e))
serial.serialutil.SerialException: write failed: [Errno 5] Input/output error
operating mode : [m4]
setting appfpga inactive
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "....../qorc-sdk/./TinyFPGA-Programmer-Application/tinyfpga-programmer-gui.py", line 706, in <module>
    adapter.set_image_info(image_index_to_set_image_info, image_info_for_image, progress, "setting image_info for App FPGA", args.checkrev, args.update)
  File "....../qorc-sdk/./TinyFPGA-Programmer-Application/tinyfpga-programmer-gui.py", line 90, in set_image_info
    with serial.Serial(self.port[0], 115200, timeout=60, writeTimeout=60) as ser:
  File "~/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "~/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

```


Can anybody give me a hand?
